param(
  [string]$IosRoot = "apps/mobile/ios",
  [string]$ExpectedAppGroup = "group.com.gomfeel.notice",
  [string]$ExpectedUrlScheme = "notice"
)

$ErrorActionPreference = "Stop"
$failed = $false

function Pass($msg) { Write-Host "[PASS] $msg" -ForegroundColor Green }
function Warn($msg) { Write-Host "[WARN] $msg" -ForegroundColor Yellow }
function Fail($msg) { Write-Host "[FAIL] $msg" -ForegroundColor Red; $script:failed = $true }

function MustExist([string]$path, [string]$label) {
  if (Test-Path $path) {
    Pass "$label exists: $path"
    return $true
  }
  Fail "$label missing: $path"
  return $false
}

$runnerAppDelegate = Join-Path $IosRoot "Runner/AppDelegate.swift"
$shareController = Join-Path $IosRoot "ShareExtension/ShareViewController.swift"
$shareInfo = Join-Path $IosRoot "ShareExtension/Info.plist"
$runnerInfo = Join-Path $IosRoot "Runner/Info.plist"
$runnerEntitlements = Join-Path $IosRoot "Runner/Runner.entitlements"
$shareEntitlements = Join-Path $IosRoot "ShareExtension/ShareExtension.entitlements"
$runnerXcodeProj = Join-Path $IosRoot "Runner.xcodeproj"
$runnerXcworkspace = Join-Path $IosRoot "Runner.xcworkspace"

$hasIosProject = (Test-Path $runnerXcodeProj) -or (Test-Path $runnerXcworkspace)
if ($hasIosProject) {
  Pass "iOS project files detected"
} else {
  Warn "Runner.xcodeproj/xcworkspace not found (likely before flutter create)"
}

$okRunner = MustExist $runnerAppDelegate "Runner AppDelegate"
$okShareController = MustExist $shareController "ShareViewController"
$okShareInfo = MustExist $shareInfo "ShareExtension Info.plist"
$okRunnerInfo = $true

if ($hasIosProject) {
  $okRunnerInfo = MustExist $runnerInfo "Runner Info.plist"
} elseif (-not (Test-Path $runnerInfo)) {
  Warn "Runner Info.plist missing (will be generated by Flutter iOS project)"
  $okRunnerInfo = $false
}

if ($okRunner) {
  $appDelegate = Get-Content -Raw $runnerAppDelegate
  if ($appDelegate -match "notice/share_extension") {
    Pass "AppDelegate MethodChannel configured"
  } else {
    Fail "AppDelegate MethodChannel(notice/share_extension) not found"
  }
}

if ($okShareController) {
  $shareCode = Get-Content -Raw $shareController
  if ($shareCode -match [regex]::Escape($ExpectedAppGroup)) {
    Pass "ShareViewController app group string found ($ExpectedAppGroup)"
  } else {
    Warn "ShareViewController app group string mismatch (expected: $ExpectedAppGroup)"
  }
}

if ($okRunnerInfo) {
  $runnerInfoXml = Get-Content -Raw $runnerInfo
  if ($runnerInfoXml -match "<key>CFBundleURLTypes</key>" -and $runnerInfoXml -match [regex]::Escape($ExpectedUrlScheme)) {
    Pass "Runner URL scheme detected ($ExpectedUrlScheme)"
  } else {
    Warn "Runner URL scheme not detected ($ExpectedUrlScheme)"
  }
}

if (Test-Path $runnerEntitlements) {
  $runnerEnt = Get-Content -Raw $runnerEntitlements
  if ($runnerEnt -match [regex]::Escape($ExpectedAppGroup)) {
    Pass "Runner entitlements app group configured"
  } else {
    Warn "Runner entitlements exists but app group is different ($ExpectedAppGroup)"
  }
} else {
  Warn "Runner.entitlements missing"
}

if (Test-Path $shareEntitlements) {
  $shareEnt = Get-Content -Raw $shareEntitlements
  if ($shareEnt -match [regex]::Escape($ExpectedAppGroup)) {
    Pass "ShareExtension entitlements app group configured"
  } else {
    Warn "ShareExtension entitlements exists but app group is different ($ExpectedAppGroup)"
  }
} else {
  Warn "ShareExtension.entitlements missing"
}

if ($failed) {
  Write-Host ""
  Write-Host "Verification failed. Fix FAIL items first." -ForegroundColor Red
  exit 1
}

Write-Host ""
Write-Host "No critical errors. Review WARN items in Xcode." -ForegroundColor Green
